ARG BASE_IMAGE="ubuntu:22.04"
ARG PANDA_VERSION="pandav0.0.27"
ARG PANDANG_VERSION="0.0.11"

### BASE IMAGE
FROM $BASE_IMAGE AS base
ARG BASE_IMAGE

# Copy dependencies lists into container. We copy them all and then do a mv because
# we need to transform base_image into a windows compatible filename which we can't
# do in a COPY command.
COPY ./debian/dependencies/* /tmp
RUN mv /tmp/$(echo "$BASE_IMAGE" | sed 's/:/_/g')_build.txt /tmp/build_dep.txt && \
    mv /tmp/$(echo "$BASE_IMAGE" | sed 's/:/_/g')_base.txt /tmp/base_dep.txt


# install dependencies
RUN apt-get -qq update && \
    DEBIAN_FRONTEND=noninteractive apt-get -qq install -y --no-install-recommends $(cat /tmp/base_dep.txt | grep -o '^[^#]*') $(cat /tmp/build_dep.txt | grep -o '^[^#]*') && \
    apt-get clean

ARG PANDA_VERSION
ARG PANDANG_VERSION
RUN wget -O /tmp/pandare.deb \
    https://github.com/panda-re/qemu/releases/download/${PANDA_VERSION}/pandare_22.04.deb && \
    wget -O /tmp/pandare-plugins.deb \
    https://github.com/panda-re/panda-ng/releases/download/v${PANDANG_VERSION}/pandare-plugins_22.04.deb && \
    apt install -yy -f /tmp/pandare.deb /tmp/pandare-plugins.deb

RUN wget -O /tmp/pandare2-${PANDANG_VERSION}-py3-none-any.whl \
    https://github.com/panda-re/panda-ng/releases/download/v${PANDANG_VERSION}/pandare2-${PANDANG_VERSION}-py3-none-any.whl && \
    pip install /tmp/pandare2-${PANDANG_VERSION}-py3-none-any.whl

RUN mkdir -p /examples
COPY ./python/examples/* /examples