/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define CONFIG_HPPA_DIS 1

#define CONFIG_I386_DIS 1

#define CONFIG_SOFTMMU 1

#define CONFIG_SYSTEM_ONLY 1

#define CONFIG_TCG 1

#define CONFIG_TCG_BUILTIN 1

#define QEMU_ARCH QEMU_ARCH_HPPA

#define TARGET_BIG_ENDIAN 1

#define TARGET_HPPA 1

#define TARGET_NAME "hppa"

#define TARGET_SUPPORTS_MTTCG 1

