/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define CONFIG_I386_DIS 1

#define CONFIG_LOONGARCH_DIS 1

#define CONFIG_SOFTMMU 1

#define CONFIG_SYSTEM_ONLY 1

#define CONFIG_TCG 1

#define CONFIG_TCG_BUILTIN 1

#define QEMU_ARCH QEMU_ARCH_LOONGARCH

#define TARGET_BIG_ENDIAN 0

#define TARGET_KVM_HAVE_GUEST_DEBUG 1

#define TARGET_LOONGARCH 1

#define TARGET_LOONGARCH64 1

#define TARGET_NAME "loongarch64"

#define TARGET_NEED_FDT 1

#define TARGET_SUPPORTS_MTTCG 1

