/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define CONFIG_I386_DIS 1

#define CONFIG_PPC_DIS 1

#define CONFIG_SOFTMMU 1

#define CONFIG_SYSTEM_ONLY 1

#define CONFIG_TCG 1

#define CONFIG_TCG_BUILTIN 1

#define QEMU_ARCH QEMU_ARCH_PPC

#define TARGET_BIG_ENDIAN 1

#define TARGET_KVM_HAVE_GUEST_DEBUG 1

#define TARGET_NAME "ppc"

#define TARGET_PPC 1

