/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define CONFIG_I386_DIS 1

#define CONFIG_SOFTMMU 1

#define CONFIG_SYSTEM_ONLY 1

#define CONFIG_TCG 1

#define CONFIG_TCG_BUILTIN 1

#define CONFIG_XTENSA_DIS 1

#define QEMU_ARCH QEMU_ARCH_XTENSA

#define TARGET_BIG_ENDIAN 1

#define TARGET_NAME "xtensaeb"

#define TARGET_SUPPORTS_MTTCG 1

#define TARGET_XTENSA 1

